pipeline {
  agent { dockerfile true }
  stages {
    stage('Test') {
      steps {
        sh '''
          python --version
          git --version
          curl --version
          pip --version
        '''
      }
    }
  }
}